# Generated by Django 4.2.1 on 2023-05-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cargo',
            field=models.IntegerField(choices=[(1, 'Gerente'), (2, 'Atendente')], null=True),
        ),
    ]
