# Generated by Django 4.2 on 2023-05-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_atendente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
