# Generated by Django 4.2 on 2023-05-25 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_atendente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependente',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependente', to='app.cliente'),
        ),
        migrations.AlterModelTable(
            name='atendente',
            table='app_funcionario',
        ),
    ]
